-- Limpieza de tablas
DELETE FROM CLIENTES_TEMP;
DELETE FROM TRANSACCIONES_LOG;

-- Reset de secuencias
ALTER SEQUENCE SEQ_CLIENTES RESTART START WITH 1;
ALTER SEQUENCE SEQ_TRANSACCIONES RESTART START WITH 1;

-- Insert de datos base
INSERT INTO PARAMETROS (CLAVE, VALOR) VALUES ('MODO', 'TEST');
