buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:4.0.12")
    }
}

plugins {
    id 'java'
    id 'idea'
    id 'org.sonarqube' version '7.2.1.6560'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    slf4jVersion = '2.0.12'
    serenityVersion = '5.3.3'
    cucumberVersion = '7.14.0'
    junitVersion = '4.13.2'
    junitLauncherVersion = '1.10.2'
    junitJupiterVersion = '5.10.2'
    assertJVersion = '3.25.3'
    logbackVersion = '1.5.6'
    poiVersion = '5.2.5'
    lombokVersion = '1.18.32'
    ojdbcVersion = '23.3.0.23.09'
}

repositories {
    maven {
        credentials {
            username 'compiler'
            password 'mUg1w4r4!$'
        }
        url "https://artifactorybancoagricola.jfrog.io/artifactory/maven-bancoagricola"
    }
    mavenLocal()
}

dependencies {
    implementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-ensure:${serenityVersion}"

    implementation "org.assertj:assertj-core:${assertJVersion}"
    implementation "junit:junit:${junitVersion}"

    implementation "org.junit.platform:junit-platform-launcher:${junitLauncherVersion}"
    implementation "org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}"
    implementation "org.junit.vintage:junit-vintage-engine:${junitJupiterVersion}"

    implementation "org.apache.poi:poi-ooxml:${poiVersion}"
    implementation "com.oracle.database.jdbc:ojdbc11:${ojdbcVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation "io.cucumber:datatable:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit:${cucumberVersion}"



    // Si estás usando Appium o pruebas móviles, descomentá la línea siguiente:
    // implementation 'io.appium:java-client:8.5.1'
}

apply plugin: "net.serenity-bdd.serenity-gradle-plugin"

test {
    testLogging.showStandardStreams = false
    systemProperties System.getProperties()
}

serenity {
    reports = ["single-page-html"]
}

gradle.startParameter.continueOnFailure = true
test.finalizedBy(aggregate)

// Forzar codificación UTF-8 para compilación
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}